# Generated by Django 3.1.6 on 2021-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210206_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('redovni', 'Redovni'), ('izvanredni', 'Izvanredni')], default='redovni', max_length=10),
        ),
    ]
